// ───────── COMPLETE LANGUAGE SYSTEM ─────────
const LANGS={
  zh:{
    langLabel:'正體中文',
    navCountdown:'倒數計時',navGoodbye:'好好告別',navStart:'開始使用',navCta:'立刻開始',
    heroJp:'生き甲斐 · 人生地圖 · 好好告別',
    heroH1:'活得<em>有意義</em>，<br>走得<em>有尊嚴</em>',
    heroSub:'找到你的 Ikigai，盤點你的人生，好好計畫你的身後事。每一刻，都值得被好好看見。',
    heroBtn1:'看看你還有多少時間 →',heroBtn2:'找到你的 Ikigai',
    heroNote:'完全免費 · 資料僅存在你的瀏覽器 · 無需註冊',
    cdEyebrow:'光陰似箭 · 一寸光陰一寸金',cdTitle:'你的人生，正在流逝',
    cdSub:'不是為了恐懼，而是為了清醒。<br>每一秒都是你無法買回的資產。',
    cdLabel:'輸入你的生日與預期壽命，開始你的人生倒數',
    cdAgeUnit:'歲',cdBtn:'開始倒數',cdPctSub:'的人生已經過去',
    cdRemaining:'剩餘',cdTickerLabel:'剩餘秒數',cdUnits:['年','月','週','天','時','分'],
    ikiEyebrow:'生き甲斐 · Ikigai',ikiH2:'你活著的理由',
    ikiSub:'Ikigai 是日文「生存的意義」。它存在於四個圓的交集：你愛的、你擅長的、世界需要的、你能維生的。',
    iki1Title:'你愛做的事',iki1Hint:'什麼事讓你忘記時間流逝？讓你充滿活力？',iki1Ph:'寫下讓你心跳加速的事...',
    iki2Title:'你擅長的事',iki2Hint:'朋友為了什麼來找你？你覺得輕鬆但別人覺得難的事？',iki2Ph:'寫下你天生就擅長的事...',
    iki3Title:'世界需要的',iki3Hint:'你希望解決什麼問題？讓世界更好的哪個方向？',iki3Ph:'寫下你看到的缺口或需求...',
    iki4Title:'能讓你維生的',iki4Hint:'你能被人付費的技能或服務是什麼？',iki4Ph:'寫下你能創造價值的方式...',
    ikiFindBtn:'找出我的 Ikigai →',ikiResultLabel:'你的 Ikigai 輪廓',
    ikigaiResult:'從你寫下的內容，你的 Ikigai 輪廓是：一個在「{a}」與「{b}」之間找到交集的人。你正在用你擅長且熱愛的方式，為世界創造你獨特的價值。繼續深挖這個交集。',
    ikigaiPartial:'你已經看見一些輪廓了。繼續填寫其他欄位，讓你的 Ikigai 更清晰完整。',
    svgLabels:['你愛做的事','你擅長的事','世界需要的','能維生的','熱情','專業','使命','志業'],
    featEy:'六個面向',featH2:'全面看見自己',featSub:'從人生意義到身後安排，最完整的人生盤點空間。',
    featCore:'核心',feat1:'一日重置協議',feat1Desc:'Dan Koe 方法論。早/中/晚三段深度提問，打破慣性，重設人生方向。',
    feat2:'Ikigai 盤點',feat2Desc:'找到你愛做、擅長、世界需要、能維生四個圓的交集，那就是你活著的理由。',
    feat3:'人生各階段回顧',feat3Desc:'童年到此刻，逐一回顧每個階段的記憶、選擇與感受。',
    feat4:'價值觀盤點',feat4Desc:'找出你真正在乎的事，設定 1/5/10 年的人生方向。',
    feat5:'遺願清單',feat5Desc:'把那些「總有一天要做的事」寫下來，然後開始一一實現。',
    feat6:'好好告別清單',feat6Desc:'臨終照顧、遺囑、葬禮、遺產、保險——五大面向完整規劃。',
    howEy:'一日重置協議',howH2:'三個時段，重設人生',
    step1Title:'反願景 + 正願景',step1Time:'☀️ 早上',step1Desc:'先直視你不想要的人生，再翻轉到你真正渴望的。這個對比是改變最強的燃料。',
    step2Title:'打破自動駕駛',step2Time:'🌤 白天',step2Desc:'在不同時刻暫停，問自己這幾個問題。大多數人一輩子都活在自動導航模式。',
    step3Title:'整合 + 設定鏡頭',step3Time:'🌙 晚上',step3Desc:'整合今天的發現，寫下核心洞見，設定三個「鏡頭」——方向感，而非硬性目標。',
    gbEy:'好好告別',gbH2:'身後事，也是愛的一部分',gbIntro:'提前規劃身後事，不是悲觀，是給自己和家人最深情的禮物。五大面向，逐一確認。',
    appEy:'開始使用',appH2:'你的人生地圖',appSub:'資料即時存在你的瀏覽器，完全私密。',
    ctaH:'準備好好看見自己了嗎？',ctaS:'只需要一個安靜的時刻，和對自己的誠實。',ctaBtn:'現在開始 →',
    footer1:'人生地圖 · 活得有意義，走得有尊嚴',footer2:'生き甲斐 · Ikigai · 好好告別',
    footer3:'資料僅存在你的瀏覽器，不上傳任何伺服器 · 完全免費',
    quoteText:'你沒有你想要的人生，是因為你還不是那個「會擁有那種人生」的人。改變不從行為開始，從身份認同開始。',
    stagesPh:'在這裡自由書寫...',stagesSaveBtn:'儲存這段記憶',
    letterSal:'親愛的 {name}，',
    toastBirthday:'請輸入你的生日',toastIkigaiEmpty:'請至少填寫一個欄位',toastIkigai:'Ikigai 已記錄 生き甲斐',
    toastMaxValues:'最多選 5 個',toastSaved:'已儲存 ✓',toastLetterSaved:'信件已封存 ✉️',
    bucketDone:'已完成 {done}/{total} 項 · {pct}%',
  },
  zhs:{
    langLabel:'简中',
    navCountdown:'倒计时',navGoodbye:'好好告别',navStart:'开始使用',navCta:'立刻开始',
    heroJp:'生き甲斐 · 人生地图 · 好好告别',
    heroH1:'活得<em>有意义</em>，<br>走得<em>有尊严</em>',
    heroSub:'找到你的 Ikigai，盘点你的人生，好好规划你的身后事。每一刻，都值得被好好看见。',
    heroBtn1:'看看你还有多少时间 →',heroBtn2:'找到你的 Ikigai',
    heroNote:'完全免费 · 数据仅存于你的浏览器 · 无需注册',
    cdEyebrow:'光阴似箭 · 一寸光阴一寸金',cdTitle:'你的人生，正在流逝',
    cdSub:'不是为了恐惧，而是为了清醒。<br>每一秒都是你无法买回的资产。',
    cdLabel:'输入你的生日与预期寿命，开始你的人生倒计时',
    cdAgeUnit:'岁',cdBtn:'开始倒计时',cdPctSub:'的人生已经过去',
    cdRemaining:'剩余',cdTickerLabel:'剩余秒数',cdUnits:['年','月','周','天','时','分'],
    ikiEyebrow:'生き甲斐 · Ikigai',ikiH2:'你活着的理由',
    ikiSub:'Ikigai 是日文「生存的意义」。它存在于四个圆的交集：你爱的、你擅长的、世界需要的、你能维生的。',
    iki1Title:'你爱做的事',iki1Hint:'什么事让你忘记时间流逝？让你充满活力？',iki1Ph:'写下让你心跳加速的事...',
    iki2Title:'你擅长的事',iki2Hint:'朋友为了什么来找你？你觉得轻松但别人觉得难的事？',iki2Ph:'写下你天生就擅长的事...',
    iki3Title:'世界需要的',iki3Hint:'你希望解决什么问题？让世界更好的哪个方向？',iki3Ph:'写下你看到的缺口或需求...',
    iki4Title:'能让你维生的',iki4Hint:'你能被人付费的技能或服务是什么？',iki4Ph:'写下你能创造价值的方式...',
    ikiFindBtn:'找出我的 Ikigai →',ikiResultLabel:'你的 Ikigai 轮廓',
    ikigaiResult:'从你写下的内容，你的 Ikigai 轮廓是：一个在「{a}」与「{b}」之间找到交集的人。你正在用你擅长且热爱的方式，为世界创造你独特的价值。继续深挖这个交集。',
    ikigaiPartial:'你已经看见一些轮廓了。继续填写其他字段，让你的 Ikigai 更清晰完整。',
    svgLabels:['你爱做的事','你擅长的事','世界需要的','能维生的','热情','专业','使命','志业'],
    featEy:'六个面向',featH2:'全面看见自己',featSub:'从人生意义到身后安排，最完整的人生盘点空间。',
    featCore:'核心',feat1:'一日重置协议',feat1Desc:'Dan Koe 方法论。早/中/晚三段深度提问，打破惯性，重设人生方向。',
    feat2:'Ikigai 盘点',feat2Desc:'找到你爱做、擅长、世界需要、能维生四个圆的交集，那就是你活着的理由。',
    feat3:'人生各阶段回顾',feat3Desc:'童年到此刻，逐一回顾每个阶段的记忆、选择与感受。',
    feat4:'价值观盘点',feat4Desc:'找出你真正在乎的事，设定 1/5/10 年的人生方向。',
    feat5:'遗愿清单',feat5Desc:'把那些「总有一天要做的事」写下来，然后开始一一实现。',
    feat6:'好好告别清单',feat6Desc:'临终照顾、遗嘱、葬礼、遗产、保险——五大面向完整规划。',
    howEy:'一日重置协议',howH2:'三个时段，重设人生',
    step1Title:'反愿景 + 正愿景',step1Time:'☀️ 早上',step1Desc:'先直视你不想要的人生，再翻转到你真正渴望的。这个对比是改变最强的燃料。',
    step2Title:'打破自动驾驶',step2Time:'🌤 白天',step2Desc:'在不同时刻暂停，问自己这几个问题。大多数人一辈子都活在自动导航模式。',
    step3Title:'整合 + 设定镜头',step3Time:'🌙 晚上',step3Desc:'整合今天的发现，写下核心洞见，设定三个「镜头」——方向感，而非硬性目标。',
    gbEy:'好好告别',gbH2:'身后事，也是爱的一部分',gbIntro:'提前规划身后事，不是悲观，是给自己和家人最深情的礼物。五大面向，逐一确认。',
    appEy:'开始使用',appH2:'你的人生地图',appSub:'数据即时存于你的浏览器，完全私密。',
    ctaH:'准备好好看见自己了吗？',ctaS:'只需要一个安静的时刻，和对自己的诚实。',ctaBtn:'现在开始 →',
    footer1:'人生地图 · 活得有意义，走得有尊严',footer2:'生き甲斐 · Ikigai · 好好告别',
    footer3:'数据仅存于你的浏览器，不上传任何服务器 · 完全免费',
    quoteText:'你没有你想要的人生，是因为你还不是那个「会拥有那种人生」的人。改变不从行为开始，从身份认同开始。',
    stagesPh:'在这里自由书写...',stagesSaveBtn:'保存这段记忆',
    letterSal:'亲爱的 {name}，',
    toastBirthday:'请输入你的生日',toastIkigaiEmpty:'请至少填写一个字段',toastIkigai:'Ikigai 已记录 生き甲斐',
    toastMaxValues:'最多选 5 个',toastSaved:'已保存 ✓',toastLetterSaved:'信件已封存 ✉️',
    bucketDone:'已完成 {done}/{total} 项 · {pct}%',
  },
  en:{
    langLabel:'EN',
    navCountdown:'Countdown',navGoodbye:'Final Farewell',navStart:'Get Started',navCta:'Start Now',
    heroJp:'Ikigai · Life Map · Final Farewell',
    heroH1:'Live with <em>Purpose</em>,<br>Die with <em>Dignity</em>',
    heroSub:'Find your Ikigai, reflect on your life, plan your legacy. Every moment deserves to be truly seen.',
    heroBtn1:'See How Much Time You Have →',heroBtn2:'Find Your Ikigai',
    heroNote:'Completely Free · Data stays in your browser · No sign-up needed',
    cdEyebrow:'Time Flies · Every Second Counts',cdTitle:'Your Life is Slipping Away',
    cdSub:'Not to cause fear, but to inspire clarity.<br>Every second is an asset you can never buy back.',
    cdLabel:'Enter your birthday and expected lifespan to start your countdown',
    cdAgeUnit:'yrs',cdBtn:'Start Countdown',cdPctSub:'of your life has passed',
    cdRemaining:'left',cdTickerLabel:'Seconds Remaining',cdUnits:['Yrs','Mos','Wks','Days','Hrs','Min'],
    ikiEyebrow:'Ikigai · 生き甲斐',ikiH2:'Your Reason for Being',
    ikiSub:"Ikigai is the Japanese concept of 'reason for being.' It lives at the intersection of four circles: what you love, what you're good at, what the world needs, and what you can be paid for.",
    iki1Title:'What You Love',iki1Hint:'What makes you lose track of time? What energizes you?',iki1Ph:'Write what makes your heart race...',
    iki2Title:"What You're Good At",iki2Hint:"What do friends come to you for? What feels easy to you but hard for others?",iki2Ph:"Write what you're naturally gifted at...",
    iki3Title:'What the World Needs',iki3Hint:'What problems do you want to solve? What would make the world better?',iki3Ph:'Write the gaps or needs you see...',
    iki4Title:'What You Can Be Paid For',iki4Hint:'What skills or services can people pay you for?',iki4Ph:'Write how you can create value...',
    ikiFindBtn:'Find My Ikigai →',ikiResultLabel:'Your Ikigai Outline',
    ikigaiResult:'From what you\'ve written, your Ikigai outline is: someone finding the intersection between "{a}" and "{b}". You\'re creating unique value for the world using what you love and excel at. Keep digging deeper into this intersection.',
    ikigaiPartial:'You\'ve glimpsed the outline. Keep filling in the other fields to make your Ikigai clearer and more complete.',
    svgLabels:['What You Love',"What You're\nGood At",'World Needs','Paid For','Passion','Profession','Mission','Vocation'],
    featEy:'Six Dimensions',featH2:'See Yourself Fully',featSub:"From life's meaning to end-of-life arrangements, the most complete life reflection space.",
    featCore:'Core',feat1:'Daily Reset Protocol',feat1Desc:'Dan Koe methodology. Three deep sessions—morning, midday, evening—to break habits and reset your life direction.',
    feat2:'Ikigai Map',feat2Desc:'Find the intersection of what you love, what you\'re good at, what the world needs, and what sustains you. That\'s your reason for living.',
    feat3:'Life Stages Review',feat3Desc:'From childhood to now, revisit each stage—its memories, choices, and feelings.',
    feat4:'Values Clarification',feat4Desc:'Identify what truly matters to you and set your direction for the next 1, 5, and 10 years.',
    feat5:'Bucket List',feat5Desc:'Write down everything you\'ve always wanted to do, then start making it happen.',
    feat6:'End-of-Life Checklist',feat6Desc:'Complete planning across five dimensions: medical care, will, funeral, estate, and insurance.',
    howEy:'Daily Reset Protocol',howH2:'Three Time Blocks to Reset Your Life',
    step1Title:'Anti-Vision + Vision',step1Time:'☀️ Morning',step1Desc:'First, face the life you don\'t want. Then flip to what you truly desire. This contrast fuels change.',
    step2Title:'Break Autopilot',step2Time:'🌤 Daytime',step2Desc:'Pause at different moments and ask yourself these questions. Most people live on autopilot forever.',
    step3Title:'Integrate + Set Lenses',step3Time:'🌙 Evening',step3Desc:'Synthesize today\'s insights, write down core realizations, and set three "lenses"—direction, not rigid goals.',
    gbEy:'Final Farewell',gbH2:'End-of-Life Planning is an Act of Love',gbIntro:"Planning ahead isn't pessimism — it's the most loving gift you can give yourself and your family.",
    appEy:'Get Started',appH2:'Your Life Map',appSub:'Your data stays in your browser, completely private.',
    ctaH:'Ready to Truly See Yourself?',ctaS:'All it takes is a quiet moment and honesty with yourself.',ctaBtn:'Begin Now →',
    footer1:'Life Map · Live with Purpose, Die with Dignity',footer2:'Ikigai · 生き甲斐 · Final Farewell',
    footer3:'Data stays in your browser only · Nothing is uploaded · Completely free',
    quoteText:"You don't have the life you want because you haven't yet become the person who would have that life. Change doesn't start with behavior — it starts with identity.",
    stagesPh:'Write freely here...',stagesSaveBtn:'Save this memory',
    letterSal:'Dear {name},',
    toastBirthday:'Please enter your birthday',toastIkigaiEmpty:'Please fill in at least one field',toastIkigai:'Ikigai recorded 生き甲斐',
    toastMaxValues:'Maximum 5 selections',toastSaved:'Saved ✓',toastLetterSaved:'Letter sealed ✉️',
    bucketDone:'Completed {done}/{total} · {pct}%',
  },
  ja:{
    langLabel:'日本語',
    navCountdown:'カウントダウン',navGoodbye:'終活',navStart:'始める',navCta:'今すぐ始める',
    heroJp:'生き甲斐 · 人生マップ · 終活',
    heroH1:'<em>意義</em>を持って生き，<br><em>尊厳</em>を持って旅立つ',
    heroSub:'生き甲斐を見つけ，人生を振り返り，終活を計画する。すべての瞬間を大切に。',
    heroBtn1:'残りの時間を確認する →',heroBtn2:'生き甲斐を見つける',
    heroNote:'完全無料 · データはブラウザのみ · 登録不要',
    cdEyebrow:'光陰矢の如し · 時は金なり',cdTitle:'あなたの人生は過ぎていく',
    cdSub:'恐怖ではなく，気づきのために。<br>すべての秒は取り戻せない資産です。',
    cdLabel:'誕生日と予想寿命を入力して，カウントダウンを開始してください',
    cdAgeUnit:'歳',cdBtn:'カウントダウン開始',cdPctSub:'の人生が過ぎました',
    cdRemaining:'残り',cdTickerLabel:'残り秒数',cdUnits:['年','ヶ月','週','日','時間','分'],
    ikiEyebrow:'生き甲斐 · Ikigai',ikiH2:'あなたが生きる理由',
    ikiSub:'生き甲斐とは「生きる意味」という日本語の概念です。四つの円の交点に存在します：愛すること，得意なこと，世界が必要とすること，収入になること。',
    iki1Title:'好きなこと',iki1Hint:'時間を忘れることは何？活力を感じることは？',iki1Ph:'胸が躍ることを書いてください...',
    iki2Title:'得意なこと',iki2Hint:'友人から頼まれることは？自分には簡単でも他人には難しいことは？',iki2Ph:'自然に得意なことを書いてください...',
    iki3Title:'世界が必要とすること',iki3Hint:'どんな問題を解決したい？世界をより良くするために？',iki3Ph:'あなたが見つけたギャップを書いてください...',
    iki4Title:'収入になること',iki4Hint:'報酬をもらえるスキルやサービスは何ですか？',iki4Ph:'価値を生み出せる方法を書いてください...',
    ikiFindBtn:'生き甲斐を見つける →',ikiResultLabel:'生き甲斐の輪郭',
    ikigaiResult:'あなたが書いたものから，生き甲斐の輪郭が見えてきました：「{a}」と「{b}」の交点を見つけた人。あなたは得意で愛することを通じて，世界に独自の価値を創造しています。この交点をさらに深く掘り下げてください。',
    ikigaiPartial:'いくつか輪郭が見えてきましたね。他の項目も埋めることで，生き甲斐がもっと鮮明で完全になります。',
    svgLabels:['好きなこと','得意なこと','世界が必要','収入になる','情熱','専門','使命','天職'],
    featEy:'六つの側面',featH2:'自分を全体的に見る',featSub:'人生の意味から終活まで，最も完全な人生振り返りスペース。',
    featCore:'コア',feat1:'日々のリセット・プロトコル',feat1Desc:'Dan Koe メソッド。朝・昼・夜の三段深い問い，習慣を破壊し人生をリセット。',
    feat2:'生き甲斐の地図',feat2Desc:'好きなこと・得意なこと・世界が必要・収入になる四つの円の交点を見つける。それがあなたの生きる理由。',
    feat3:'人生各段階の回顧',feat3Desc:'幼少期から今まで，各段階の記憶・選択・感情をひとつずつ振り返る。',
    feat4:'価値観の明確化',feat4Desc:'本当に大切なことを見つけ，1年・5年・10年の人生方向を設定。',
    feat5:'バケットリスト',feat5Desc:'「いつかしたい」とずっと思っていることを書き出し，一つずつ実現する。',
    feat6:'終活チェックリスト',feat6Desc:'医療・遺言・葬儀・遺産・保険──五つの側面から完全に計画。',
    howEy:'日々のリセット・プロトコル',howH2:'三つの時間帯で人生をリセット',
    step1Title:'反ビジョン＋ビジョン',step1Time:'☀️ 朝',step1Desc:'まず，望まない人生と向き合う。次に，本当に望む姿に翻す。この対比が変化の最強の燃料。',
    step2Title:'オートパイロットを破る',step2Time:'🌤 昼',step2Desc:'昼間のさまざまな時刻に一時停止し，自分に問いかける。ほとんどの人は一生自動操縦のまま。',
    step3Title:'統合＋レンズを設定',step3Time:'🌙 夜',step3Desc:'今日の気づきを統合し，核となる洞察を書き，三つの「レンズ」を設定。方向性であり，硬い目標ではなく。',
    gbEy:'終活',gbH2:'身後の準備は愛の行為',gbIntro:'事前に計画することは悲観的ではありません。それは自分と家族へ最も深い愛のギフト。',
    appEy:'始める',appH2:'あなたの人生マップ',appSub:'データはブラウザに保存され，完全にプライベートです。',
    ctaH:'自分を本当に見つめる準備はできていますか？',ctaS:'必要なのは静かな時間と自分への誠実さだけ。',ctaBtn:'今すぐ始める →',
    footer1:'人生マップ · 意義を持って生き，尊厳を持って旅立つ',footer2:'生き甲斐 · Ikigai · 終活',
    footer3:'データはブラウザのみ保存 · サーバーへの送信なし · 完全無料',
    quoteText:'あなたが望む人生を持っていないのは，まだその人生を持つべき人になっていないから。変化は行動からではなく，アイデンティティから始まります。',
    stagesPh:'ここに自由に書いてください...',stagesSaveBtn:'この思い出を保存',
    letterSal:'尊い {name} へ，',
    toastBirthday:'お誕生日を入力してください',toastIkigaiEmpty:'最低1つ入力してください',toastIkigai:'生き甲斐を記録しました 生き甲斐',
    toastMaxValues:'最大5つまで選択できます',toastSaved:'保存しました ✓',toastLetterSaved:'手紙を封じました ✉️',
    bucketDone:'{done}/{total} 完了 · {pct}%',
  },
};

function buildFeatures(){
  const t=LANGS[currentLang];
  const feats=[
    {icon:'🔥',title:t.feat1,desc:t.feat1Desc,core:true},
    {icon:'生き甲斐',title:t.feat2,desc:t.feat2Desc},
    {icon:'🕰️',title:t.feat3,desc:t.feat3Desc},
    {icon:'🧭',title:t.feat4,desc:t.feat4Desc},
    {icon:'✨',title:t.feat5,desc:t.feat5Desc},
    {icon:'📋',title:t.feat6,desc:t.feat6Desc},
  ];
  document.getElementById('featGrid').innerHTML=feats.map(f=>`
    <div class="fc${f.core?' hi':''}">
      <span class="fc-icon">${f.icon}</span>
      <div class="fc-title">${f.title}</div>
      <div class="fc-desc">${f.desc}</div>
    </div>`).join('');
  if(feats[0])document.querySelector('.fc.hi').setAttribute('data-hi-label',t.featCore);
}

function buildSteps(){
  const t=LANGS[currentLang];
  const steps=[
    {num:'01',time:t.step1Time,title:t.step1Title,desc:t.step1Desc},
    {num:'02',time:t.step2Time,title:t.step2Title,desc:t.step2Desc},
    {num:'03',time:t.step3Time,title:t.step3Title,desc:t.step3Desc},
  ];
  document.getElementById('stepsList').innerHTML=steps.map(s=>`
    <div class="step">
      <div class="step-num">${s.num}</div>
      <div>
        <div class="step-time">${s.time}</div>
        <h3 class="step-h">${s.title}</h3>
        <p class="step-p">${s.desc}</p>
      </div>
    </div>`).join('');
}

function updateDateLabels(){
  const t=LANGS[currentLang];
  const now=new Date();
  document.getElementById('lDt').textContent=now.toLocaleDateString(currentLang==='ja'?'ja-JP':currentLang==='zhs'?'zh-CN':'zh-TW');
  const year=now.getFullYear();
  const sigTexts={zh:`愛你的 我 · ${year}年`,zhs:`爱你的 我 · ${year}年`,en:`With love · ${year}`,ja:`愛する者より · ${year}年`};
  document.getElementById('lSig').textContent=sigTexts[currentLang]||sigTexts.zh;
}
